#!/usr/bin/env python3
"""
csv_to_candidates.py — converts a spreadsheet of your real candidate roster
into the candidates.json format this app expects.

USAGE
    python3 csv_to_candidates.py roster.csv candidates.json

INPUT CSV
    Export your roster (e.g. from Excel/Google Sheets) as a CSV with a
    header row containing these columns (any order, case-insensitive):

        candidateId, name, mobile, password, set, center, batchStart, batchEnd

    - candidateId : any unique string, e.g. "SCTPC-1001"
    - mobile      : 10-digit mobile number (used to log in)
    - password    : the candidate's login password (plain text -- see
                    README.md "Security Notes" before using real passwords)
    - set         : must be exactly "Set 1" through "Set 6"
    - center      : must be exactly "Center 1" through "Center 10"
                    (or your own center names/labels -- just be consistent)
    - batchStart / batchEnd : date+time the candidate may log in, in
                    ISO 8601 with the +05:30 offset, e.g.
                    2026-09-15T09:00:00+05:30

    A ready-to-fill template is written alongside this script the first
    time you run it with no arguments: `python3 csv_to_candidates.py`
    creates roster_template.csv for you to copy and fill in Excel.

OUTPUT
    Writes a candidates.json with the same shape the app already ships
    with (including the informational "_meta" block), ready to replace
    the demo file.
"""
import csv
import json
import sys
import re

REQUIRED_COLUMNS = ["candidateid", "name", "mobile", "password", "set", "center", "batchstart", "batchend"]

TEMPLATE_ROWS = [
    ["candidateId", "name", "mobile", "password", "set", "center", "batchStart", "batchEnd"],
    ["SCTPC-1001", "K. Ramesh Babu", "9000000001", "ChangeMe@1001", "Set 1", "Center 1", "2026-09-15T09:00:00+05:30", "2026-09-15T12:00:00+05:30"],
]


def write_template():
    with open("roster_template.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerows(TEMPLATE_ROWS)
    print("No input file given -- wrote roster_template.csv you can open in Excel/Sheets, fill in, save as CSV, then run:")
    print("    python3 csv_to_candidates.py roster.csv candidates.json")


def normalize_header(h):
    return re.sub(r"[^a-z]", "", h.strip().lower())


def convert(csv_path, out_path):
    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            print("ERROR: CSV has no header row.")
            sys.exit(1)
        header_map = {normalize_header(h): h for h in reader.fieldnames}
        missing = [c for c in REQUIRED_COLUMNS if c not in header_map]
        if missing:
            print(f"ERROR: CSV is missing required column(s): {missing}")
            print(f"Found columns: {reader.fieldnames}")
            sys.exit(1)

        candidates = []
        seen_ids = set()
        seen_mobiles = set()
        errors = []
        for i, row in enumerate(reader, start=2):  # row 1 is the header
            def get(col):
                return (row.get(header_map[col]) or "").strip()

            cid = get("candidateid")
            mobile = get("mobile")
            set_name = get("set")
            center = get("center")

            if not cid:
                errors.append(f"Row {i}: missing candidateId")
                continue
            if cid in seen_ids:
                errors.append(f"Row {i}: duplicate candidateId '{cid}'")
                continue
            if not re.fullmatch(r"\d{10}", mobile):
                errors.append(f"Row {i} ({cid}): mobile '{mobile}' is not exactly 10 digits")
            if mobile in seen_mobiles:
                errors.append(f"Row {i} ({cid}): duplicate mobile number '{mobile}'")
            if set_name not in [f"Set {n}" for n in range(1, 7)]:
                errors.append(f"Row {i} ({cid}): set '{set_name}' is not one of 'Set 1'..'Set 6'")

            seen_ids.add(cid)
            seen_mobiles.add(mobile)
            candidates.append({
                "candidateId": cid,
                "name": get("name"),
                "mobile": mobile,
                "password": get("password"),
                "set": set_name,
                "center": center,
                "batchStart": get("batchstart"),
                "batchEnd": get("batchend"),
            })

        if errors:
            print(f"Found {len(errors)} problem(s) in the CSV -- fix these and re-run:")
            for e in errors[:50]:
                print("  -", e)
            if len(errors) > 50:
                print(f"  ... and {len(errors) - 50} more")
            sys.exit(1)

        out = {
            "_meta": {
                "note": f"Generated by csv_to_candidates.py from {csv_path}. {len(candidates)} candidates.",
                "timezone": "Asia/Kolkata (+05:30)",
            },
            "candidates": candidates,
        }
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2, ensure_ascii=False)
        print(f"Wrote {out_path} with {len(candidates)} candidates.")


if __name__ == "__main__":
    if len(sys.argv) == 1:
        write_template()
    elif len(sys.argv) == 3:
        convert(sys.argv[1], sys.argv[2])
    else:
        print(__doc__)
        sys.exit(1)
